// Single source of truth for the generative banner animations.
// Used by the Lab gallery and the admin banner picker.

export const ANIMATIONS = [
  { id: 'julia', name: 'julia set', type: 'pixel', isNew: true,
    blurb: 'A cousin of the Mandelbrot set: iterate z = z\u00b2 + c for every pixel and colour it by how long it takes to escape. Here c drifts in a circle.',
    witty: 'Infinite detail, finite patience.' },
  { id: 'lorenz', name: 'lorenz attractor', type: 'pixel', isNew: true,
    blurb: 'Three coupled differential equations from weather modelling, integrated forever. The path never repeats yet never leaves its butterfly.',
    witty: 'The original butterfly effect, no butterflies harmed.' },
  { id: 'kaleido', name: 'kaleidoscope', type: 'pixel', isNew: true,
    blurb: 'A plasma field folded across six mirrored wedges, so every wobble is reflected into symmetry.',
    witty: 'Symmetry: the cheat code for looking expensive.' },
  { id: 'fireworks', name: 'fireworks', type: 'pixel', isNew: true,
    blurb: 'Rockets launch, decelerate, and burst into gravity-bound particles that fade as they fall.',
    witty: 'All of the spectacle, none of the fire-safety paperwork.' },
  { id: 'pendulum', name: 'double pendulum', type: 'pixel', isNew: true,
    blurb: 'Two linked pendulums under real physics. Deterministic, yet so sensitive to starting conditions it looks random.',
    witty: 'Chaos theory, but you can watch it sweat.' },
  { id: 'phyllotaxis', name: 'phyllotaxis', type: 'pixel', isNew: true,
    blurb: 'Florets placed by the golden angle, 137.5\u00b0 apart \u2014 the exact spiral a sunflower uses to pack seeds.',
    witty: 'Nature\u2019s favourite irrational number, showing off.' },
  { id: 'sand', name: 'falling sand', type: 'pixel', isNew: true,
    blurb: 'A cellular automaton where each grain falls down or tumbles diagonally, piling into little dunes.',
    witty: 'An ant farm for people with no ants.' },
  { id: 'globe', name: 'wireframe globe', type: 'ascii', isNew: true,
    blurb: 'A sphere of evenly spaced dots rotated in 3D, with the far side dimmed to fake depth.',
    witty: 'A whole planet rendered in two characters.' },
  { id: 'automata', name: 'cellular automaton', type: 'ascii', isNew: true,
    blurb: 'A one-dimensional rule (110, 30, 90\u2026) applied row after row. Rule 110 alone is Turing-complete.',
    witty: 'Four bits of rule, infinite consequences.' },
  { id: 'snake', name: 'snake (autoplay)', type: 'ascii', isNew: true,
    blurb: 'The Nokia classic, played by a greedy little algorithm that chases the nearest food and avoids eating itself.',
    witty: 'High score: still trying. Forever.' },
  { id: 'fire', name: 'doom fire', type: 'ascii',
    blurb: 'The 1993 Doom fire algorithm: seed a hot row at the bottom, then cool and scatter it upward. Convection appears for free.',
    witty: 'It is, technically, a controlled fire on your homepage.' },
  { id: 'voronoi', name: 'voronoi drift', type: 'pixel',
    blurb: 'Every pixel takes the colour of its nearest of nine roaming seeds; the bright seams are the borders between territories.',
    witty: 'Gerrymandering, but at least it looks good.' },
  { id: 'cube', name: 'wireframe cube', type: 'ascii',
    blurb: 'Eight vertices and twelve edges rotated in 3D and projected down to ASCII, with glyphs fading by depth.',
    witty: 'All the dimensions, none of the GPU.' },
  { id: 'tunnel', name: 'warp tunnel', type: 'pixel',
    blurb: 'A polar texture mapping where screen distance becomes depth and angle becomes the wall. Scroll both and you fly forever.',
    witty: 'Going nowhere, very fast, on purpose.' },
  { id: 'maze', name: '10 print maze', type: 'ascii',
    blurb: 'The one-line Commodore 64 classic: random forward and back slashes that the eye stitches into an endless labyrinth.',
    witty: '10 PRINT, 20 stare, 30 GOTO 10.' },
  { id: 'metaballs', name: 'metaballs', type: 'pixel',
    blurb: 'Five smooth field sources summed together; wherever their glow overlaps, the surfaces merge like mercury.',
    witty: 'A lava lamp, minus the questionable dorm room.' },
  { id: 'ripple', name: 'interference', type: 'pixel',
    blurb: 'Several sine-wave sources overlapped so their crests and troughs add and cancel into a shifting moire.',
    witty: 'Throw three stones in a pond and watch them argue.' },
  { id: 'lissajous', name: 'lissajous', type: 'pixel',
    blurb: 'A single point traced by two perpendicular sine waves at a 3:2 ratio, with a slowly turning phase and a glowing trail.',
    witty: 'What your oscilloscope doodles when it is bored.' },
  { id: 'matrix', name: 'digital rain', type: 'ascii',
    blurb: 'Columns of glyphs falling at random speeds, each with a bright leading character and a fading tail.',
    witty: 'Yes, there is no spoon. Please keep moving.' },
  { id: 'neural', name: 'neural net', type: 'ascii',
    blurb: 'Four layers of nodes with signals rippling left to right along every connection as activations pulse.',
    witty: 'Thinking. Allegedly.' },
  { id: 'terminal', name: 'boot log', type: 'ascii',
    blurb: 'A fake startup sequence typing itself out character by character, complete with a blinking block cursor.',
    witty: 'It passes its own tests every single time.' },
  { id: 'blackhole', name: 'event horizon', type: 'ascii',
    blurb: 'An accretion disk in ASCII, with relativistic beaming brightening the side that rotates toward you.',
    witty: 'Spaghettification, now available in monospace.' },
  { id: 'thermal', name: 'thermal map', type: 'ascii',
    blurb: 'Moving heat sources drive a field of glyphs through a blue-to-white temperature ramp.',
    witty: 'Every actuator\u2019s least favourite portrait.' },
  { id: 'starfield', name: 'starfield', type: 'pixel',
    blurb: 'Stars accelerating outward from a vanishing point, with short streaks to sell the warp.',
    witty: 'Hyperspace, on a budget of exactly zero.' },
  { id: 'plasma', name: 'plasma', type: 'pixel',
    blurb: 'Stacked sine functions of position and time mapped onto the palette \u2014 the original demoscene flex.',
    witty: 'Older than you, and somehow cooler too.' },
  { id: 'swarm', name: 'boids', type: 'pixel',
    blurb: 'Each dot obeys three rules \u2014 separate, align, cohere \u2014 and flocking emerges with no leader at all.',
    witty: 'Anarchy that somehow files in formation.' },
  { id: 'gears', name: 'gear train', type: 'pixel',
    blurb: 'Two meshing gears turning in opposite directions, with shaded teeth and little hub spokes.',
    witty: 'Backlash sold separately.' },
  { id: 'scope', name: 'oscilloscope', type: 'pixel',
    blurb: 'A scrolling sweep drawing a live sine and PWM trace with phosphor-style persistence.',
    witty: 'Where control loops go to confess.' },
  { id: 'circuit', name: 'pcb pulses', type: 'pixel',
    blurb: 'A lattice of traces and pads with signal pulses racing along the copper, leaving short trails.',
    witty: 'Current events, in the most literal sense.' },
  { id: 'motor', name: 'bldc motor', type: 'pixel',
    blurb: 'A cross-section of a brushless motor: rotor poles, stator teeth and a commutation field sweeping around.',
    witty: 'A magnet, lied to twenty thousand times a second.' },
  { id: 'helix', name: 'dna helix', type: 'pixel',
    blurb: 'Two sine strands a half-turn apart with rungs between them; the front strand is drawn brighter for depth.',
    witty: 'The original open-source hardware.' },
  { id: 'life', name: 'game of life', type: 'pixel',
    blurb: 'Conway\u2019s four rules on a wrap-around grid; cells shift colour with age and reseed when life stalls.',
    witty: 'Zero players. Infinite drama.' },
];

export const HINTS = {
  motor: 'drag left/right to spin it', gears: 'drag left/right to drive them',
  scope: 'move to bend the waveform', swarm: 'move to lead the flock, click to scatter',
  life: 'move or click to seed cells', circuit: 'click to inject pulses',
  cube: 'move to rotate it by hand', helix: 'move to twist and spin',
  terminal: 'hover to fast-forward the boot',
  julia: 'move to reshape the fractal', lorenz: 'move left/right to orbit it',
  phyllotaxis: 'move to shift the bloom', globe: 'move to spin and tilt it',
  kaleido: 'move to shift the focus', tunnel: 'move to steer', plasma: 'move to drag the core',
  starfield: 'move to steer, the warp follows', metaballs: 'move to add a blob',
  ripple: 'move to drop ripples', voronoi: 'move to add a cell', thermal: 'move to add heat',
  fire: 'move to wave the torch', maze: 'move to stir the slashes',
  matrix: 'move to speed up a column', neural: 'move to light up neurons',
  sand: 'move to pour sand', pendulum: 'click to kick it', automata: 'click for a new rule',
  fireworks: 'click to launch one',
};

export const ANIMATION_BY_ID = Object.fromEntries(ANIMATIONS.map((a) => [a.id, a]));
